title: Stackbit Starter Theme
baseURL: /
params:
  header:
    title: SPECR
    has_nav: true
    nav_links:
      - label: Log In
        url: app.specr.ie
        style: primary
  footer:
    has_nav: true
    nav_links: []
    has_social: true
    social_links:
      - label: GitHub
        url: 'https://github.com/'
        style: link
        new_window: true
      - label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: link
        new_window: true
    content: '&copy; Specr. All rights reserved.'
  domain: 'http://calm-rock-06c23e810.azurestaticapps.net'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
