title: Specr
baseURL: /
params:
  header:
    title: SPECR
    has_nav: true
    nav_links:
      - label: Log In
        url: 'https://app.specr.ie'
        style: primary
  footer:
    has_nav: true
    nav_links: []
    has_social: true
    social_links: []
    content: '&copy; Specr. All rights reserved.'
  domain: 'http://specr.ie'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
